CREATE DATABASE IF NOT EXISTS virtubell;
USE virtubell;
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

ALTER TABLE users
ADD CONSTRAINT unique_email UNIQUE (email);
